<?php
header('Content-Type: application/json; charset=utf-8');
error_reporting(E_ERROR | E_PARSE);
$helper = $this->params()->fromQuery('helper','');
$log = $this->logger();
$rs=null;
$user = $this->identity();

switch ($helper) {
    case 'sql':
        $params = $this->params()->fromQuery();
        $rs = $this->GenerateurSql($params);
        echo $this->json($rs);                
        break;
    case 'generate':
        $params = $this->params()->fromQuery();
        $m = $this->MoteurFactory(true,true);
        echo $this->json($m->genereConcept($params));                
        break;
    }


?>



